title: LanTel Cloud Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"


# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.png"

collections:
    collection-one:
      permalink: "/:docs/:(Draadloze) Headsets/"
      output: true
    collection-two:
      permalink: "/:docs/:Algemene informatie LanTel Cloud diensten/"
      output: true
  just_the_docs:
    collections:
      collection-one:
        name: Collection One
        nav_fold: true
      collection-two:
        name: Collection Two
        nav_fold: false