title: LanTel Cloud Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"


# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.png"

# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  Algemene informatie LanTel Cloud diensten:
    permalink: "/:collection/:path/"
    output: true
  (Draadloze) Headsets:
    permalink: "/:collection/:path/"
    output: true
  Aurora TeleQ:
    permalink: "/:collection/:path/"
    output: true
  CloudCTI:
    permalink: "/:collection/:path/"
    output: true
  E-Fax:
    permalink: "/:collection/:path/"
    output: true
  LanTel Blue - Univerge Blue:
    permalink: "/:collection/:path/"
    output: true
  LanTel Mobiel:
    permalink: "/:collection/:path/"
    output: true
  LanTel Move - Avaya:
    permalink: "/:collection/:path/"
    output: true
  LanTel Teams Bellen:
    permalink: "/:collection/:path/"
    output: true
  LanTel Wave - Enreach Contact:
    permalink: "/:collection/:path/"
    output: true


just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the collections
    Algemene informatie LanTel Cloud diensten:
      # Give the collection a name
      name: Algemene informatie LanTel Cloud diensten
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Fold the collection in the navigation
      # Supports true or false (default)
      nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
    (Draadloze) Headsets:
      name: (Draadloze) Headsets
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    Aurora TeleQ:
      name: Aurora TeleQ
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    CloudCTI:
      name: CloudCTI
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    E-Fax:
      name: E-Fax
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    LanTel Blue - Univerge Blue:
      name: LanTel Blue - Univerge Blue
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    LanTel Mobiel:
      name: LanTel Mobiel
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    LanTel Move - Avaya:
      name:LanTel Move - Avaya
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    LanTel Teams Bellen:
      name: LanTel Teams Bellen
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    LanTel Wave - Enreach Contact:
      name: LanTel Wave - Enreach Contact
      nav_exclude: false
      nav_fold: true
      search_exclude: false